name: LimitedTime
author: QuickScythe
version: 3.5.1
description: Limit playtime to a configured time per player.
api-version: 1.20
api: Spigot
main: me.quickscythe.lt.LimitedTime
commands:
  playtime:
    usage: /playtime help
    description: Main command
    aliases:
      - pt
      - ptime
      - playt
      - plt
  hologram:
    usage: /hologram create
    aliases:
      - holo